/**
 * Mule GetStaisfaction Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module.getsatisfaction;

import org.junit.Assert;
import org.junit.Test;


public class GetSatisfactionConnectorTest
{
	
	public GetSatisfactionConnectorTest() {}
	
	@Test
	public void basicTest() {
		Assert.assertNotNull(new Object());
	}    
}
